services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: unless-stopped
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=MelleWessel123"
    ports:
      - "1433:1433"

volumes:
  sql_data:
    driver: local